apiVersion: ocular.crashoverride.run/v1beta1
kind: ClusterDownloader
metadata:
  name: chalkmark-extract
spec:
  container:
    name: chalkmark-extract
    image: chalkular-downloader:latest
    imagePullPolicy: IfNotPresent
    env: []
    volumeMounts: []
    resources:
      limits:
        cpu: 500m
        memory: 128Mi
      requests:
        cpu: 10m
        memory: 64Mi
  metadataFiles:
    - chalk.json
  parameters:
    - name: INSECURE_REGISTRY
      default: ""
      description: "If set to a non-empty value, registry connection uses http"
  volumes: []
