apiVersion: ocular.crashoverride.run/v1beta1
kind: ClusterUploader
metadata:
  name: results
spec:
  container:
    name: results-extract
    image: chalkular-uploader:latest
    imagePullPolicy: IfNotPresent
    env: []
    volumeMounts: []
  parameters:
    - name: S3_BUCKET
      description: "The S3 bucket to upload to"
    - name: S3_REGION
      default: "us-east-1"
      description: "AWS Region to use"
  volumes: []
