apiVersion: ocular.crashoverride.run/v1beta1
kind: ClusterUploader
metadata:
  name: results
spec:
  container:
    name: results-extract
    image: chalkular-uploader:latest
    imagePullPolicy: IfNotPresent
    env:
      - name: CHALKULAR_INGEST_TOKEN
        valueFrom:
          secretKeyRef:
            key: ingest-token
            name: chalkular-secrets
            optional: true
    volumeMounts: []
  parameters:
    - name: S3_BUCKET
      description: "The S3 bucket to upload to"
    - name: S3_REGION
      default: "us-east-1"
      description: "AWS Region to use"
    - name: S3_PREFIX
      default: ""
      description: "a prefix to append to all objects created"
    - name: WORKSPACE_ID
      default: ""
      description: "The workspace ID that the report belongs to"
    - name: ACTION_ID
      default: ""
      description: "The action ID of the report"
    - name: METADATA_ID
      default: ""
      description: "The metadata ID of the resource scanned"
  volumes: []
