apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: chalkular
    app.kubernetes.io/managed-by: kustomize
  annotations:
    chalk.ocular.crashoverride.run/type: controller-manager
  name: controller-manager
  namespace: system
