//go:build !ignore_autogenerated

// Copyright (C) 2025-2026 Crash Override, Inc.
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the FSF, either version 3 of the License, or (at your option) any later version.
// See the LICENSE file in the root of this repository for full license text or
// visit: <https://www.gnu.org/licenses/gpl-3.0.html>.

// Code generated by controller-gen. DO NOT EDIT.

package v1beta1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ChalkReportPolicy) DeepCopyInto(out *ChalkReportPolicy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ChalkReportPolicy.
func (in *ChalkReportPolicy) DeepCopy() *ChalkReportPolicy {
	if in == nil {
		return nil
	}
	out := new(ChalkReportPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ChalkReportPolicy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ChalkReportPolicyExtraction) DeepCopyInto(out *ChalkReportPolicyExtraction) {
	*out = *in
	if in.DownloaderParams != nil {
		in, out := &in.DownloaderParams, &out.DownloaderParams
		*out = new(string)
		**out = **in
	}
	if in.ProfileParams != nil {
		in, out := &in.ProfileParams, &out.ProfileParams
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ChalkReportPolicyExtraction.
func (in *ChalkReportPolicyExtraction) DeepCopy() *ChalkReportPolicyExtraction {
	if in == nil {
		return nil
	}
	out := new(ChalkReportPolicyExtraction)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ChalkReportPolicyList) DeepCopyInto(out *ChalkReportPolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ChalkReportPolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ChalkReportPolicyList.
func (in *ChalkReportPolicyList) DeepCopy() *ChalkReportPolicyList {
	if in == nil {
		return nil
	}
	out := new(ChalkReportPolicyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ChalkReportPolicyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ChalkReportPolicySpec) DeepCopyInto(out *ChalkReportPolicySpec) {
	*out = *in
	in.Extraction.DeepCopyInto(&out.Extraction)
	in.PipelineTemplate.DeepCopyInto(&out.PipelineTemplate)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ChalkReportPolicySpec.
func (in *ChalkReportPolicySpec) DeepCopy() *ChalkReportPolicySpec {
	if in == nil {
		return nil
	}
	out := new(ChalkReportPolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ChalkReportPolicyStatus) DeepCopyInto(out *ChalkReportPolicyStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ChalkReportPolicyStatus.
func (in *ChalkReportPolicyStatus) DeepCopy() *ChalkReportPolicyStatus {
	if in == nil {
		return nil
	}
	out := new(ChalkReportPolicyStatus)
	in.DeepCopyInto(out)
	return out
}
