//go:build !ignore_autogenerated

// Copyright (C) 2025-2026 Crash Override, Inc.
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the FSF, either version 3 of the License, or (at your option) any later version.
// See the LICENSE file in the root of this repository for full license text or
// visit: <https://www.gnu.org/licenses/gpl-3.0.html>.

// Code generated by controller-gen. DO NOT EDIT.

package v1beta1

import (
	apiv1beta1 "github.com/crashappsec/ocular/api/v1beta1"
	"k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ArtifactMediaTypeMapping) DeepCopyInto(out *ArtifactMediaTypeMapping) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ArtifactMediaTypeMapping.
func (in *ArtifactMediaTypeMapping) DeepCopy() *ArtifactMediaTypeMapping {
	if in == nil {
		return nil
	}
	out := new(ArtifactMediaTypeMapping)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ArtifactMediaTypeMapping) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ArtifactMediaTypeMappingDownloader) DeepCopyInto(out *ArtifactMediaTypeMappingDownloader) {
	*out = *in
	if in.Value != nil {
		in, out := &in.Value, &out.Value
		*out = new(apiv1beta1.DownloaderSpec)
		(*in).DeepCopyInto(*out)
	}
	out.ValueFrom = in.ValueFrom
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ArtifactMediaTypeMappingDownloader.
func (in *ArtifactMediaTypeMappingDownloader) DeepCopy() *ArtifactMediaTypeMappingDownloader {
	if in == nil {
		return nil
	}
	out := new(ArtifactMediaTypeMappingDownloader)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ArtifactMediaTypeMappingDownloaderStatus) DeepCopyInto(out *ArtifactMediaTypeMappingDownloaderStatus) {
	*out = *in
	if in.Ref != nil {
		in, out := &in.Ref, &out.Ref
		*out = new(v1.ObjectReference)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ArtifactMediaTypeMappingDownloaderStatus.
func (in *ArtifactMediaTypeMappingDownloaderStatus) DeepCopy() *ArtifactMediaTypeMappingDownloaderStatus {
	if in == nil {
		return nil
	}
	out := new(ArtifactMediaTypeMappingDownloaderStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ArtifactMediaTypeMappingList) DeepCopyInto(out *ArtifactMediaTypeMappingList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ArtifactMediaTypeMapping, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ArtifactMediaTypeMappingList.
func (in *ArtifactMediaTypeMappingList) DeepCopy() *ArtifactMediaTypeMappingList {
	if in == nil {
		return nil
	}
	out := new(ArtifactMediaTypeMappingList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ArtifactMediaTypeMappingList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ArtifactMediaTypeMappingProfile) DeepCopyInto(out *ArtifactMediaTypeMappingProfile) {
	*out = *in
	if in.Value != nil {
		in, out := &in.Value, &out.Value
		*out = new(apiv1beta1.ProfileSpec)
		(*in).DeepCopyInto(*out)
	}
	out.ValueFrom = in.ValueFrom
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ArtifactMediaTypeMappingProfile.
func (in *ArtifactMediaTypeMappingProfile) DeepCopy() *ArtifactMediaTypeMappingProfile {
	if in == nil {
		return nil
	}
	out := new(ArtifactMediaTypeMappingProfile)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ArtifactMediaTypeMappingProfileStatus) DeepCopyInto(out *ArtifactMediaTypeMappingProfileStatus) {
	*out = *in
	if in.Ref != nil {
		in, out := &in.Ref, &out.Ref
		*out = new(v1.ObjectReference)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ArtifactMediaTypeMappingProfileStatus.
func (in *ArtifactMediaTypeMappingProfileStatus) DeepCopy() *ArtifactMediaTypeMappingProfileStatus {
	if in == nil {
		return nil
	}
	out := new(ArtifactMediaTypeMappingProfileStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ArtifactMediaTypeMappingSpec) DeepCopyInto(out *ArtifactMediaTypeMappingSpec) {
	*out = *in
	if in.MediaTypes != nil {
		in, out := &in.MediaTypes, &out.MediaTypes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	in.Profile.DeepCopyInto(&out.Profile)
	in.Downloader.DeepCopyInto(&out.Downloader)
	if in.TTLSecondsAfterFinished != nil {
		in, out := &in.TTLSecondsAfterFinished, &out.TTLSecondsAfterFinished
		*out = new(int32)
		**out = **in
	}
	if in.TTLSecondsMaxLifetime != nil {
		in, out := &in.TTLSecondsMaxLifetime, &out.TTLSecondsMaxLifetime
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ArtifactMediaTypeMappingSpec.
func (in *ArtifactMediaTypeMappingSpec) DeepCopy() *ArtifactMediaTypeMappingSpec {
	if in == nil {
		return nil
	}
	out := new(ArtifactMediaTypeMappingSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ArtifactMediaTypeMappingStatus) DeepCopyInto(out *ArtifactMediaTypeMappingStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Profile != nil {
		in, out := &in.Profile, &out.Profile
		*out = new(ArtifactMediaTypeMappingProfileStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.Downloader != nil {
		in, out := &in.Downloader, &out.Downloader
		*out = new(ArtifactMediaTypeMappingDownloaderStatus)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ArtifactMediaTypeMappingStatus.
func (in *ArtifactMediaTypeMappingStatus) DeepCopy() *ArtifactMediaTypeMappingStatus {
	if in == nil {
		return nil
	}
	out := new(ArtifactMediaTypeMappingStatus)
	in.DeepCopyInto(out)
	return out
}
