//go:build !ignore_autogenerated

// Copyright (C) 2025-2026 Crash Override, Inc.
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the FSF, either version 3 of the License, or (at your option) any later version.
// See the LICENSE file in the root of this repository for full license text or
// visit: <https://www.gnu.org/licenses/gpl-3.0.html>.

// Code generated by controller-gen. DO NOT EDIT.

package v1beta1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MediaTypePolicy) DeepCopyInto(out *MediaTypePolicy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MediaTypePolicy.
func (in *MediaTypePolicy) DeepCopy() *MediaTypePolicy {
	if in == nil {
		return nil
	}
	out := new(MediaTypePolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MediaTypePolicy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MediaTypePolicyDownloaderStatus) DeepCopyInto(out *MediaTypePolicyDownloaderStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MediaTypePolicyDownloaderStatus.
func (in *MediaTypePolicyDownloaderStatus) DeepCopy() *MediaTypePolicyDownloaderStatus {
	if in == nil {
		return nil
	}
	out := new(MediaTypePolicyDownloaderStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MediaTypePolicyList) DeepCopyInto(out *MediaTypePolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]MediaTypePolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MediaTypePolicyList.
func (in *MediaTypePolicyList) DeepCopy() *MediaTypePolicyList {
	if in == nil {
		return nil
	}
	out := new(MediaTypePolicyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MediaTypePolicyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MediaTypePolicyProfileStatus) DeepCopyInto(out *MediaTypePolicyProfileStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MediaTypePolicyProfileStatus.
func (in *MediaTypePolicyProfileStatus) DeepCopy() *MediaTypePolicyProfileStatus {
	if in == nil {
		return nil
	}
	out := new(MediaTypePolicyProfileStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MediaTypePolicySpec) DeepCopyInto(out *MediaTypePolicySpec) {
	*out = *in
	if in.MediaTypes != nil {
		in, out := &in.MediaTypes, &out.MediaTypes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	in.PipelineTemplate.DeepCopyInto(&out.PipelineTemplate)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MediaTypePolicySpec.
func (in *MediaTypePolicySpec) DeepCopy() *MediaTypePolicySpec {
	if in == nil {
		return nil
	}
	out := new(MediaTypePolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MediaTypePolicyStatus) DeepCopyInto(out *MediaTypePolicyStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	out.Profile = in.Profile
	out.Downloader = in.Downloader
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MediaTypePolicyStatus.
func (in *MediaTypePolicyStatus) DeepCopy() *MediaTypePolicyStatus {
	if in == nil {
		return nil
	}
	out := new(MediaTypePolicyStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PipelineTemplate) DeepCopyInto(out *PipelineTemplate) {
	*out = *in
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PipelineTemplate.
func (in *PipelineTemplate) DeepCopy() *PipelineTemplate {
	if in == nil {
		return nil
	}
	out := new(PipelineTemplate)
	in.DeepCopyInto(out)
	return out
}
